name: Terraform Preview

on:
  push:
    branches:
      - github-actions
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  ROLE_SESSION_NAME: terraform-gha

defaults:
  run:
    shell: bash
    working-directory: terraform/

jobs:
  terraform-format:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive

  terraform-modules:
    name: Terraform Modules
    runs-on: ubuntu-latest
    needs: terraform-format
    strategy:
      matrix:
        folder:
          - modules/alb
          - modules/ec2
          - modules/rds
          - modules/s3
          - modules/vpc
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=${{ matrix.folder }} init

      - name: Terraform Validate
        run: terraform -chdir=${{ matrix.folder }} validate

      - name: Create tfvars file
        run: echo "${{ secrets.TFVARS_CONTENT }}" | base64 -d > temp.tfvars
      - name: Terraform Plan
        run: |
          TFVARS_PATH="$(pwd)/temp.tfvars"
          if [ -f "$TFVARS_PATH" ]; then
            terraform -chdir=${{ matrix.folder }} plan -var-file="$TFVARS_PATH"
          else
            echo "Error: tfvars file not found at $TFVARS_PATH"
            exit 1
          fi

  terraform-environments:
    name: Terraform Environments
    runs-on: ubuntu-latest
    needs: [terraform-format, terraform-modules]
    strategy:
      max-parallel: 1
      matrix:
        folder:
          - environment/dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=${{ matrix.folder }} init

      - name: Terraform Validate
        run: terraform -chdir=${{ matrix.folder }} validate

      - name: Create tfvars file
        run: echo "${{ secrets.TFVARS_CONTENT }}" > temp.tfvars

      - name: Terraform Plan
        run: |
          TFVARS_PATH="$(pwd)/temp.tfvars"
          if [ -f "$TFVARS_PATH" ]; then
            terraform -chdir=${{ matrix.folder }} plan -var-file="$TFVARS_PATH"
          else
            echo "Error: tfvars file not found at $TFVARS_PATH"
            exit 1
          fi
