name: Terraform Preview

on:
  push:
    branches:
      - github-actions
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  ROLE_SESSION_NAME: terraform-gha

defaults:
  run:
    shell: bash
    working-directory: terraform/

jobs:
  terraform-preview:
    name: Terraform Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Format
        run: terraform fmt -check -recursive
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate (All Directories)
        run: |
          find . -type f -name '*.tf' -printf '%h\n' | sort -u | while read dir; do
            echo "Validating $dir"
            cd "$dir"
            terraform init
            terraform validate
            cd - > /dev/null
          done
      - name: Terraform Plan (All Directories)
        run: |
          find . -type f -name '*.tf' -printf '%h\n' | sort -u | while read dir; do
            echo "Planning $dir"
            cd "$dir"
            terraform init
            terraform plan
            cd - > /dev/null
          done
