name: Terraform Preview

on:
  push:
    branches:
      - github-actions
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  ROLE_SESSION_NAME: terraform-gha

defaults:
  run:
    shell: bash
    working-directory: terraform/

jobs:
  terraform-format:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive

  terraform-modules:
    name: Terraform Modules
    runs-on: ubuntu-latest
    needs: terraform-format
    strategy:
      matrix:
        module_path:
          - modules/alb
          - modules/ec2
          - modules/rds
          - modules/s3
          - modules/vpc
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=${{ matrix.module_path }} init

      - name: Terraform Validate
        run: terraform -chdir=${{ matrix.module_path }} validate

  terraform-environments:
    name: Terraform Environments
    runs-on: ubuntu-latest
    needs: [terraform-format, terraform-modules]
    strategy:
      matrix:
        # 学習のため拡張性を考慮した記述にしているが本件ではdev環境のみ
        environment_path:
          - environment/dev
    env:
      TF_VAR_key_name: ${{ secrets.TF_VAR_KEY_NAME }}
      TF_VAR_db_username: ${{ secrets.TF_VAR_DB_USERNAME }}
      TF_VAR_ssh_cidr_blocks: ${{ secrets.TF_VAR_SSH_CIDR_BLOCKS }}
      TF_VAR_common_tags: ${{ vars.TF_VAR_COMMON_TAGS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=${{ matrix.environment_path }} init

      - name: Terraform Validate
        run: terraform -chdir=${{ matrix.environment_path }} validate

      - name: Terraform Plan
        run: terraform -chdir=${{ matrix.environment_path }} plan

      - name: Terraform Apply
        id: terraform-apply
        run: terraform -chdir=${{ matrix.environment_path }} apply -auto-approve

      - name: Slack Notification (Terraform Apply Result)
        if: always()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: "C090A5GC4TG"
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Finished Terraform Apply",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
              "text": "Terraform Apply completed: ${{ format('<{0}/{1}/actions/runs/{2}>', github.server_url, github.repository, github.run_id) }}"                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
