name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
      - github-actions
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  ROLE_SESSION_NAME: terraform-gha
  SLACK_CHANNEL_ID: C090A5GC4TG

defaults:
  run:
    shell: bash
    working-directory: terraform/

jobs:
  terraform-format-all:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive

  terraform-validate-modules:
    name: Terraform Validate Modules
    runs-on: ubuntu-latest
    needs: terraform-format-all
    strategy:
      matrix:
        module_path:
          - modules/alb
          - modules/ec2
          - modules/rds
          - modules/s3
          - modules/vpc
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=${{ matrix.module_path }} init

      - name: Terraform Validate
        run: terraform -chdir=${{ matrix.module_path }} validate

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: terraform-validate-modules
    outputs:
      TF_PLAN_EXITCODE: ${{ steps.terraform-plan.outputs.exitcode }}
    strategy:
      matrix:
        # 学習のため拡張性を考慮した記述にしているが本件ではdev環境のみ
        environment_path:
          - environment/dev
    env:
      TF_VAR_key_name: ${{ secrets.TF_VAR_KEY_NAME }}
      TF_VAR_db_username: ${{ secrets.TF_VAR_DB_USERNAME }}
      TF_VAR_ssh_cidr_blocks: ${{ secrets.TF_VAR_SSH_CIDR_BLOCKS }}
      TF_VAR_common_tags: ${{ vars.TF_VAR_COMMON_TAGS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=${{ matrix.environment_path }} init

      - name: Terraform Validate
        run: terraform -chdir=${{ matrix.environment_path }} validate

      - name: Terraform Plan
        id: terraform-plan
        continue-on-error: true
        run: terraform -chdir=${{ matrix.environment_path }} plan -detailed-exitcode

      - name: Slack Notification (Request for Approval)
        if: steps.terraform-plan.outputs.exitcode == '2'
        uses: ./.github/actions/slack-approval-request
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ env.SLACK_CHANNEL_ID }}
          github-server-url: ${{ github.server_url }}
          github-repository: ${{ github.repository }}
          github-run-id: ${{ github.run_id }}

  terraform-deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: needs.terraform-plan.outputs.TF_PLAN_EXITCODE == 2
    environment:
      name: "${{ matrix.environment_path }}"
    strategy:
      matrix:
        environment_path:
          - environment/dev
    env:
      TF_VAR_key_name: ${{ secrets.TF_VAR_KEY_NAME }}
      TF_VAR_db_username: ${{ secrets.TF_VAR_DB_USERNAME }}
      TF_VAR_ssh_cidr_blocks: ${{ secrets.TF_VAR_SSH_CIDR_BLOCKS }}
      TF_VAR_common_tags: ${{ vars.TF_VAR_COMMON_TAGS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=${{ matrix.environment_path }} init

      - name: Terraform Apply
        id: terraform-apply
        run: terraform -chdir=${{ matrix.environment_path }} apply -auto-approve

      - name: Slack Notification (Terraform Apply Result)
        if: always()
        uses: ./.github/actions/slack-deploy-result
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ env.SLACK_CHANNEL_ID }}
          job-status: ${{ job.status }}
          github-server-url: ${{ github.server_url }}
          github-repository: ${{ github.repository }}
          github-run-id: ${{ github.run_id }}
